# Utiliser l'image officielle Ubuntu
FROM ubuntu:latest

# Mettre à jour les paquets et logiciels
RUN apt-get update && apt-get install -y

# Afficher Hello, World! quand le conteneur est exécuté
CMD ["echo", "Hello, World!"]
